name = "tou-rate-generator"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 * * * *"]

[vars]
FIREBASE_API_KEY=""
FIREBASE_AUTH_DOMAIN=""
FIREBASE_PROJECT_ID=""
FIREBASE_STORAGE_BUCKET=""
FIREBASE_MESSAGING_SENDER_ID=""
FIREBASE_APP_ID=""
FIREBASE_MEASUREMENT_ID=""